version: '3.8'
services:
  db:
    image: postgres:13.3-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.4
    container_name: redis
    restart: always
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  migrate:
    image: migrate/migrate
    container_name: migrate
    command: -database "postgres://postgres:postgres@localhost:5432/crm?sslmode=disable" -path /usr/src/app/module/object/migration up
    volumes:
      - ./backend:/usr/src/app
    network_mode: host
    restart: 'no'
    depends_on:
      - db

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local