package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
)

// World is the resolver for the world field.
func (r *mutationResolver) World(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: World - world"))
}

// Hello is the resolver for the hello field.
func (r *queryResolver) Hello(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Hello - hello"))
}
